export const categoriesData = {
  plywood: {
    title: "Plywood",
    items: [
      {
        id: 1,
        title: "Premium Plywood",
        desc: "High strength and durability",
        img: "https://premierply.in/wp-content/uploads/2023/09/1628161591-product-image-2.jpg",
        isNew: true,
        isTrending: false,
        price: 500,
      },
      {
        id: 2,
        title: "Marine Plywood",
        desc: "Water-resistant & long-lasting",
        img: "https://premierply.in/wp-content/uploads/2023/09/1689766423-product-image-929x1024-1.png",
        isNew: false,
        isTrending: true,
        price: 900,
      },
      {
        id: 3,
        title: "Premium Plywood",
        desc: "High strength and durability",
        img: "https://premierply.in/wp-content/uploads/2023/09/1628161591-product-image-2.jpg",
        isNew: true,
        isTrending: false,
        price: 500,
      },
      {
        id: 4,
        title: "Marine Plywood",
        desc: "Water-resistant & long-lasting",
        img: "https://premierply.in/wp-content/uploads/2023/09/1689766423-product-image-929x1024-1.png",
        isNew: false,
        isTrending: true,
        price: 900,
      },
      {
        id: 5,
        title: "Premium Plywood",
        desc: "High strength and durability",
        img: "https://premierply.in/wp-content/uploads/2023/09/1628161591-product-image-2.jpg",
        isNew: true,
        isTrending: false,
        price: 500,
      },
      {
        id: 6,
        title: "Marine Plywood",
        desc: "Water-resistant & long-lasting",
        img: "https://premierply.in/wp-content/uploads/2023/09/1689766423-product-image-929x1024-1.png",
        isNew: false,
        isTrending: true,
        price: 900,
      },
      {
        id: 7,
        title: "Premium Plywood",
        desc: "High strength and durability",
        img: "https://premierply.in/wp-content/uploads/2023/09/1628161591-product-image-2.jpg",
        isNew: true,
        isTrending: false,
        price: 500,
      },
      {
        id: 8,
        title: "Marine Plywood",
        desc: "Water-resistant & long-lasting",
        img: "https://premierply.in/wp-content/uploads/2023/09/1689766423-product-image-929x1024-1.png",
        isNew: false,
        isTrending: true,
        price: 900,
      }
    ]
  },

  doors: {
    title: "Doors",
    items: [
      {
        id: 1,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 2,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 3,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 4,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 5,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 6,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 7,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 8,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      }
    ]
  }
};
