export const categoriesData = [
  {
    id: "Modular Kitche",
    title: "Modular Kitchen",
    title_tagline:"Designed to work beautifully. Built to last.",
    title_disc:"A kitchen is the heart of a home — a place where families gather, stories are shared, meals are crafted, and life unfolds.At Space By Signature, Our modular kitchens are designed around how you move, think, and live — making every interaction intuitive and every surface purposeful.From the way a drawer glides, to how lighting sets the mood, to the quiet utility hidden behind seamless panels — every detail is engineered for comfort, convenience, and longevity.Because a kitchen should not only look refined —it should feel effortless to live in.Not just built for today —crafted to grow with you.",
    disc: "akjfbaksfakfka",
    url: "https://premierply.in/wp-content/uploads/2023/09/1689766423-product-image-929x1024-1.png",
    items: [
      {
        id: 1,
        title: "Premium Plywood",
        desc: "High strength and durability",
        img: "https://premierply.in/wp-content/uploads/2023/09/1628161591-product-image-2.jpg",
        isNew: true,
        isTrending: false,
        price: 500,
      },
      {
        id: 2,
        title: "Marine Plywood",
        desc: "Water-resistant & long-lasting",
        img: "https://premierply.in/wp-content/uploads/2023/09/1689766423-product-image-929x1024-1.png",
        isNew: false,
        isTrending: true,
        price: 900,
      },
      {
        id: 3,
        title: "Premium Plywood",
        desc: "High strength and durability",
        img: "https://premierply.in/wp-content/uploads/2023/09/1628161591-product-image-2.jpg",
        isNew: true,
        isTrending: false,
        price: 500,
      },
      {
        id: 4,
        title: "Marine Plywood",
        desc: "Water-resistant & long-lasting",
        img: "https://premierply.in/wp-content/uploads/2023/09/1689766423-product-image-929x1024-1.png",
        isNew: false,
        isTrending: true,
        price: 900,
      },
      {
        id: 5,
        title: "Premium Plywood",
        desc: "High strength and durability",
        img: "https://premierply.in/wp-content/uploads/2023/09/1628161591-product-image-2.jpg",
        isNew: true,
        isTrending: false,
        price: 500,
      },
      {
        id: 6,
        title: "Marine Plywood",
        desc: "Water-resistant & long-lasting",
        img: "https://premierply.in/wp-content/uploads/2023/09/1689766423-product-image-929x1024-1.png",
        isNew: false,
        isTrending: true,
        price: 900,
      },
      {
        id: 7,
        title: "Premium Plywood",
        desc: "High strength and durability",
        img: "https://premierply.in/wp-content/uploads/2023/09/1628161591-product-image-2.jpg",
        isNew: true,
        isTrending: false,
        price: 500,
      },
      {
        id: 8,
        title: "Marine Plywood",
        desc: "Water-resistant & long-lasting",
        img: "https://premierply.in/wp-content/uploads/2023/09/1689766423-product-image-929x1024-1.png",
        isNew: false,
        isTrending: true,
        price: 900,
      },
    ],
  },

  {
    id: "Wardrobe",
    title: "Wardrobe",
    title_tagline:"Designed for clarity. Built for effortless living.",
    title_disc:" A wardrobe is a private space — a reflection of who you are and how you live.Our modular wardrobe solutions are crafted to offer structure, convenience, and beauty, while adapting to your lifestyle and routines.Soft lighting, smooth mechanisms, customizable shelving, and tailored storage systems ensure every item has a place — from everyday essentials to treasured pieces.Every element — from shelf height to drawer configuration to lighting placement — is planned with intention. Premium finishes, precision hardware, and thoughtful internal systems create a wardrobe that feels intuitive, elegant, and deeply personal.Because the best spaces don’t just look organized —they make life feel lighter.",
    disc: "jkasfkjasfiasgk",
    url: "https://images.unsplash.com/photo-1622372738946-62e02505feb3?q=80&w=532&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    items: [
      {
        id: 1,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 2,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 3,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 4,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 5,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 6,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 7,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 8,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
    ],
  },

  {
    id: "Bar Cabinet",
    title: "Bar Cabinet",
    title_tagline:"Where craft meets celebration",
    title_disc:"A bar isn’t just a corner for bottles — it’s a statement of personality, leisure, and refined taste.At Space by Signature, we design bar cabinets that bring sophistication, warmth and functionality into one elevated experience.Every detail — from the choice of finishes and textured veneers to soft-close hardware and ambient lighting — is curated to feel intentional, not incidental.Built with precision, designed with sensibility, and customised to complement your lifestyle — our bar cabinets don’t just store, they celebrate.Because at the end of the day, luxury is not excess —it’s how a space makes you feel.",
    disc: "tjasfasbgkasghj",
    url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=876&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    items: [
      {
        id: 1,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 2,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 3,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 4,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 5,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 6,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 7,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 8,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
    ],
  },

  {
    id: "Furniture",
    title: "Furniture",
    title_tagline:"Furniture That Feels Like Home.",
    title_disc:"Furniture should feel personal — not generic.That’s why we design everything with intention: comfort, functionality, proportion, and aesthetic balance.At Space by Signature, every piece is thoughtfully designed to reflect comfort, elegance, and timeless craftsmanship. We work closely to understand your lifestyle, preferences, and routines, ensuring every design feels personal and purposeful.From luxurious sofas and dining sets to ergonomic office furniture, outdoor pieces, club seating, ottomans, tables, and accent chairs — each category is crafted with careful detailing, refined materials, and superior functionality. Our expert designers and craftsmen blend modern technology with fine artisanal finishing to create furniture that doesn’t just fill a space — it completes it.Whether it's a statement accent chair, a custom sectional sofa, or a handcrafted dining table, every piece is built to last, styled to elevate, and designed to make everyday living a beautiful experience.",
    disc: "vehajdbmahsgsamf",
    url: "https://images.unsplash.com/photo-1581783458534-001a466b5487?q=80&w=1615&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    subCategories: [
      {
        id: "Sofa",
        name: "sofa",
        disc: "jashfkasbak",
        url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=876&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        items: [
          {
            id: 1,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 2,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 3,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 4,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 5,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 6,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 7,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 8,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
        ],
      },

      {
        id: "Table",
        name: "Table",
        disc: "a,sjnfaagasg",
        url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=876&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        items: [
          {
            id: 1,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 2,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 3,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 4,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 5,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 6,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 7,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 8,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
        ],
      },

      {
        id: "Comfy Chairs",
        name: "Comfy Chairs",
        disc: "asfasgasgag",
        url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=876&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        items: [
          {
            id: 1,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 2,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 3,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 4,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 5,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 6,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 7,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 8,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
        ],
      },

      {
        id: "Dining Table",
        name: "Dining Table",
        disc: "asgasgasgag",
        url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=876&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        items: [
          {
            id: 1,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 2,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 3,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 4,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 5,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 6,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 7,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 8,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
        ],
      },
    ],
  },

  {
    id: "Finishing Touches",
    title: "Finishing Touches",
    title_tagline:"The details that elevate design into emotion.",
    title_disc:"Whether it’s a home, a lounge, a suite, or a commercial environment, the right finishing details turn good design into unforgettable spaces.Our collection of artefacts, mood lighting, custom rugs, and curated paintings adds definition, ambiance, and sophistication — elevating the space with meaning and visual harmony.",
    disc: "vehajdbmahsgsamf",
    url: "https://premierply.in/wp-content/uploads/2023/09/1689766423-product-image-929x1024-1.png",
    subCategories: [
      {
        id: "Artefacts",
        name: "Artefacts",
        disc: "lkqihwtqkgkqq",
        url: "https://premierply.in/wp-content/uploads/2023/09/1689766423-product-image-929x1024-1.png",
        items: [
          {
            id: 1,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 2,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 3,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 4,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 5,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 6,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 7,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 8,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
        ],
      },

      {
        id: "Lamps",
        name: "Lamps",
        disc: "lqijtkqntqkmtbmw",
        url: "https://premierply.in/wp-content/uploads/2023/09/1689766423-product-image-929x1024-1.png",
        items: [
          {
            id: 1,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 2,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 3,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 4,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 5,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 6,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 7,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 8,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
        ],
      },

      {
        id: "Painting",
        name: "Painting",
        disc: "lihqankgngskag",
        url: "https://premierply.in/wp-content/uploads/2023/09/1689766423-product-image-929x1024-1.png",
        items: [
          {
            id: 1,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 2,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 3,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 4,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 5,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 6,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 7,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 8,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
        ],
      },

      {
        id: "Custom Rugs",
        name: "Custom Rugs",
        disc: "aj,shfabfagmng,as",
        url: "https://premierply.in/wp-content/uploads/2023/09/1689766423-product-image-929x1024-1.png",
        items: [
          {
            id: 1,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 2,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 3,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 4,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 5,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 6,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 7,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
          {
            id: 8,
            title: "Classic Door",
            desc: "Strong, elegant wooden door",
            img: "https://i.ibb.co/4fQ5cLq/door.png",
            isNew: true,
            isTrending: true,
            price: 1500,
          },
        ],
      },
    ],
  },

  {
    id: "Club Lights & Sound System",
    title: "Club Lights & Sound System",
    title_tagline:"Where light becomes the vibe.",
    title_disc:"Club lighting isn’t just about brightness — it’s about creating mood, rhythm, and identity.Our lighting solutions are crafted to enhance ambience, elevate design elements, and guide emotional experience — from relaxed lounge environments to dynamic nightlife moments.Each system is customised, intuitive, and seamlessly integrated into the architecture for effortless control and an elevated experience.",
    disc: "tjasfasbgkasghj",
    url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=876&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    items: [
      {
        id: 1,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 2,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 3,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 4,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 5,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 6,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 7,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 8,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
    ],
  },

  {
    id: "Home Theathre Solutions",
    title: "Home Theathre Solutions",
    title_tagline:"A great home theatre doesn’t just play a movie — it transports you.",
    title_disc:"At Space by Signature, we create immersive theatre environments where every detail works together: rich surround audio, breathtaking visuals, acoustic balance, lighting control, and premium seating.Whether you're watching an intense thriller or a quiet documentary, the experience feels intimate, powerful, and theatre-grade — right inside your home.Your favourite stories deserve a space just as unforgettable.",
    disc: "tjasfasbgkasghj",
    url: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?q=80&w=876&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    items: [
      {
        id: 1,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 2,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 3,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 4,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 5,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 6,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 7,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 8,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
    ],
  },

  {
    id: "System Window",
    title: "System Window",
    title_tagline:"Precision in form. Perfection in function.",
    title_disc:"System windows should do more than close a space — they should open possibilities.Our curated window systems are crafted for people who love light-filled mornings, uninterrupted views, and interiors that breathe.Every profile is tested for weather resistance, acoustic comfort, security, and smooth operation — ensuring years of effortless use. With minimal frames and expansive glass, we preserve aesthetics while maximising performance.Because your home deserves windows that feel intuitive, beautiful, and built for real living — not just installation.",
    disc: "tjasfasbgkasghj",
    url: "https://images.unsplash.com/photo-1581783458534-001a466b5487?q=80&w=1615&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    items: [
      {
        id: 1,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 2,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 3,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 4,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 5,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 6,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 7,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
      {
        id: 8,
        title: "Classic Door",
        desc: "Strong, elegant wooden door",
        img: "https://i.ibb.co/4fQ5cLq/door.png",
        isNew: true,
        isTrending: true,
        price: 1500,
      },
    ],
  },
];
